### PR TITLE
fix: 1540 add_expectation_suite doesn't have key overwrite_existing

### PR DESCRIPTION
**Pull request by einavfiterTB**
Fix https://github.com/ydataai/ydata-profiling/pull/1540 remove keyword argument 'overwrite_existing'.
This aligns with the changes made in https://github.com/great-expectations/great_expectations/pull/7117, great_expectations/data_context/data_context/abstract_data_context.py

### CODE REVIEW

**Comment by nadavshatz** [comment]
thanks! I missed it in #1540

**Comment by einavfiterTB** [comment]
Would appreciate the check here, we're already working with patch in production. Thanks! 🙏

**Review by alexbarros — APPROVED** [review]

**Comment by alexbarros** [comment]
@einavfiterTB just checked and it is a :+1: , can you just adjust the [unit test](https://github.com/ydataai/ydata-profiling/blob/8523d1567d1dd41978162e95ddb7d7383e3c9e2e/tests/unit/test_ge_integration.py#L95-L97)  so we can merge it?

**Comment by einavfiterTB** [comment]
@alexbarros apologies for the delay, I've updated the unit test 🙏

**Pull request merged**
