### PR TITLE
chore(deps): upgrade to pydantic-2

### PR DESCRIPTION
**Pull request by ndesaunais**
This PR aims at
- upgrade pydantic dependency to version 2
- update and fix code and test after upgrade

### CODE REVIEW

**Comment by aquemy** [comment]
@ndesaunais thank you for opening this PR!

There are a couple of issues:
1. the PR title should be `chores(deps)`
2. the tests are failing:
```
pytest tests/unit/
ImportError while loading conftest '/home/runner/work/ydata-profiling/ydata-profiling/tests/conftest.py'.
tests/conftest.py:7: in <module>
    from ydata_profiling.config import Settings
src/ydata_profiling/__init__.py:7: in <module>
    from ydata_profiling.compare_reports import compare
src/ydata_profiling/compare_reports.py:9: in <module>
    from ydata_profiling.config import Correlation, Settings
src/ydata_profiling/config.py:8: in <module>
    from pydantic_settings import BaseSettings, SettingsConfigDict
E   ModuleNotFoundError: No module named 'pydantic_settings'
make: *** [Makefile:10: test] Error 4
Error: Process completed with exit code 2.
```

You can test locally using `pytest test/unit`.

**Comment by ndesaunais** [comment]
@aquemy Thank you for launching the ci.

I realigned with conventional commits (that's the reason of the force push).

There is still one failing test I reproduce locally that I don't understand the intent of, it's called `def test_modular_absent(tdf):`

On that test, we generate a report with some `kwargs` argument set to None. The test expects not to have some header on the html, yet the the previous behavior of the report was to provide some configuration when some None arguments are passed. See `Config.shorthands` definition. 

I don't know who is right; if we pass `correlations=None`, do we expect some default to take over, or do we expect not to have any correlations at all ? I'll keep investigating, if my understanding of the code is valid, in the meanwhile if you have any insights, please let me know

**Comment by ndesaunais** [comment]
Hello @aquemy,

Thank you for launching the ci multiple times along the way.

Now everything seems to be working fine. The only failing is the linting, which fails to pull the `renovate/pydantic-2` instead of the actual name of the branch in your repo `ndesaunais:renovate/pydantic-2`. I don't want to change that workflow as it's unrelated to this actual PR.

**Comment by aquemy** [comment]
> Hello @aquemy,
> 
> Thank you for launching the ci multiple times along the way.
> 
> Now everything seems to be working fine. The only failing is the linting, which fails to pull the `renovate/pydantic-2` instead of the actual name of the branch in your repo `ndesaunais:renovate/pydantic-2`. I don't want to change that workflow as it's unrelated to this PR.
> 
> Can you have a look at it ?

Hi @ndesaunais,

Thanks you for your time and effort to make this working!

Regarding the error, this might be a small misconfiguration in the CI. I bet that it does not take into account the fork prefix when looking for a branch. 
@vascoalramos could you eventually take a look at this? If it is too complicated to adjust the CI, I'll just create a similar branch from @ndesaunais fork to the main repo.

**Comment by ndesaunais** [comment]
Hello @aquemy,

What's the update on this ?

**Comment by pmhaddad** [comment]
Hello all!

I was lurking around this **PR** due to a dependency incompatibility in a repo of mine, and noticed that another **PR** updating to `pydantic` 2 has already being merged in October 2023 (**PR** #1483). I am mentioning it here to make it easier for people to find it!

**Comment by fabclmnt** [comment]
Hi @ndesaunais ,

thank you for your contribution. Can you please update your PR with the latest changes from dev?

**Comment by ndaWefox** [comment]
@fabclmnt Can you instead close this PR ?

The work has been done by [PR 1483](https://github.com/ydataai/ydata-profiling/pull/1483).

As an individual contributor I can not close it

**Comment by ndesaunais** [comment]
Closing because [PR 1483](https://github.com/ydataai/ydata-profiling/pull/1483) already does the job

**Pull request closed without merging**
