### PR TITLE
chore(deps): remove seaborn upper limit

### PR DESCRIPTION
**Pull request by ggydush**
Seaborn 0.13 fixes an issue with annotating heatmaps and I'd like to be able to use ydata-profiling in a repository that needs this fix.

I checked git blame and didn't see a reason for the upper-bound pin. I tested on 0.13.2 with Python 3.10 and all unit tests passed.

### CODE REVIEW

**Review by fabclmnt — CHANGES_REQUESTED** [review]
Hi @ggydush ,

thank you for your contribution. Nevertheless, and due to past experiences where new minor releases from packages like numpy, seaborn or matplotlib have broken the functionality of ydata-profiling we have decided to analyze case by case the versions that we support. 

We can consider upgrading seaborn, but we will need to define an upper version.

**Comment by ggydush** [comment]
Would you be okay with upper pin on latest (0.13.2) provided tests pass?

**Comment by fabclmnt** [comment]
Yes totally! That would do.

**Review by fabclmnt — APPROVED** [review]

**Comment by ggydush** [comment]
Thank you for approving! Is there any chance this could be included in the next release?

**Comment by alexbarros** [comment]
@fabclmnt pode fazer o merge o erro do lint message era um erro do actions que jah foi corrigido

**Comment by fabclmnt** [comment]
@ggydush yes this will be included for the next release. Probably either this week or beginning of the next.

Thank you for your contribution.

**Pull request merged**
